"""empty message

Revision ID: 2f3765b8a298
Revises: cb852ab81808
Create Date: 2023-07-19 20:25:51.252669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3765b8a298'
down_revision = 'cb852ab81808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('project_account_manager_id_fkey', type_='foreignkey')
        batch_op.drop_column('account_manager_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_manager_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('project_account_manager_id_fkey', 'user', ['account_manager_id'], ['id'])

    # ### end Alembic commands ###
