"""empty message

Revision ID: cfa7f20eb378
Revises: 2f3765b8a298
Create Date: 2023-07-19 21:00:59.215190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa7f20eb378'
down_revision = '2f3765b8a298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_manager_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['account_manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_manager_id')

    # ### end Alembic commands ###
